import { Poppins } from "next/font/google"
import { Toaster } from "react-hot-toast"
import { ContextProvider } from "@/providers/ContextProvider"
import "./globals.css"

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata = {
	title: "Plesk",
	description: "Generated by create next app"
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<ContextProvider>
				<body className={poppins.className}>
					<Toaster />
					{children}
				</body>
			</ContextProvider>
		</html>
	)
}
